# Generated by Django 4.2.6 on 2023-11-28 04:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kelompok', models.CharField(choices=[('satu', 'I (Satu)'), ('dua', 'II (Dua)'), ('tiga', 'III (Tiga)'), ('empat', 'IV (Empat)'), ('lima', 'V (Lima)')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Toast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('PAGI', 'PAGI'), ('SIANG', 'SIANG'), ('MALAM', 'MALAM')], max_length=10)),
                ('datetime', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('siren_one', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('siren_two', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('siren_three', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('siren_four', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('seiscomp_one', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('seiscomp_two', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('toast_one', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('toast_two', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('disseminate_one', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('disseminate_two', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('tsp', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('wrs', models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False)),
                ('temperature1', models.CharField(max_length=10)),
                ('temperature2', models.CharField(max_length=10)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='checklist.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
