# Generated by Django 4.2.6 on 2023-11-28 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toast',
            name='siren_one',
            field=models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False, help_text='testes'),
        ),
    ]
