# Generated by Django 4.2.6 on 2023-11-28 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_alter_toast_siren_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='toast',
            name='seiscomp_three',
            field=models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False),
        ),
    ]
