# Generated by Django 4.2.6 on 2023-11-28 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_group'),
        ('checklist', '0004_toast_seiscomp_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toast',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group', to='account.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
    ]
