# Generated by Django 4.2.6 on 2023-12-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_alter_toast_group_delete_group'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toast',
            old_name='tsp',
            new_name='tsp_one',
        ),
        migrations.AddField(
            model_name='toast',
            name='tsp_two',
            field=models.BooleanField(choices=[('True', 'Ya'), ('False', 'Tidak')], default=False),
        ),
    ]
